Fix linker error with some wx installs
With some installs, `wx-config --cxxflags` has a trailing space. This
causes the following xml node to be generated:
`<compilerflag value="" />`

This breaks compilation with the following error:
```
Error: g++: warning: : linker input file unused because linking not done
g++: error: : linker input file not found: No such file or directory
```

This patch fixes that problem by removing all trailing whitespace prior
to splitting on the space character.